name = "MatterModels"
uuid = "89b7eb7d-0b8d-5078-86d5-4a0f481f2984"
version = "0.1.0"
authors = ["Uwe Hernandez Acosta <u.hernandez@hzdr.de>"]

[deps]
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
QEDcore = "35dc0263-cb5f-4c33-a114-1d7f54ab753e"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
LogExpFunctions = "0.3.29"
QEDcore = "0.4.0"
QuadGK = "2.11.2"
SpecialFunctions = "2.6.1"
Unitful = "1.25.1"
julia = "1.10"
